"""Generate Windows version metadata from Sikumon's authoritative version constant."""

from __future__ import annotations

import argparse
import tomllib
from pathlib import Path

from sikumon.config.constants import APP_VERSION


def numeric_version(version: str) -> tuple[int, int, int, int]:
    parts = version.split(".")
    if len(parts) != 3 or any(not part.isdigit() for part in parts):
        raise ValueError("APP_VERSION must use numeric major.minor.patch format")
    return int(parts[0]), int(parts[1]), int(parts[2]), 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    project = tomllib.loads((args.project_root / "pyproject.toml").read_text(encoding="utf-8"))
    package_version = str(project["project"]["version"])
    if package_version != APP_VERSION:
        raise RuntimeError(
            f"Version mismatch: pyproject={package_version!r}, runtime={APP_VERSION!r}"
        )

    version_tuple = numeric_version(APP_VERSION)
    dotted = ", ".join(str(part) for part in version_tuple)
    content = f"""# Generated by packaging/generate_version_info.py; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({dotted}),
    prodvers=({dotted}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('FileDescription', 'Sikumon Hebrew meeting assistant'),
        StringStruct('FileVersion', '{APP_VERSION}'),
        StringStruct('InternalName', 'Sikumon'),
        StringStruct('OriginalFilename', 'Sikumon.exe'),
        StringStruct('ProductName', 'Sikumon'),
        StringStruct('ProductVersion', '{APP_VERSION}')
      ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(APP_VERSION)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
